<?xml version="1.0"?>
<robot name="roscontrol" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="robot_length" value="0.5"/>
    <xacro:property name="robot_width" value="0.5"/>
    <xacro:property name="robot_height" value="0.2"/>
    <xacro:property name="wheeldiam" value="0.15"/>
    <xacro:property name="wheel_len" value="0.05"/>
    <xacro:property name="pi" value="3.14159265359"/>
    <xacro:property name="base_mass" value="15"/>
    <xacro:property name="robot_wheel_mass" value="5"/>

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
                     iyy="1.0" iyz="0.0" 
                     izz="1.0"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${robot_length} ${robot_width} ${robot_height}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${robot_length} ${robot_width} ${robot_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${base_mass}"/>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
            <inertia 
      			ixx="0.3625" ixy="0"           ixz="0"
      			                  iyy="0.3625" iyz="0"
      			                                    izz="0.625"
      		/>
        </inertial>
    </link>

    <xacro:macro name="wheel" params="prefix suffix x_reflect y_reflect">

        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> -->
                <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
                <geometry>
                    <cylinder radius="${wheeldiam/2}" length="${wheel_len}"/>
                </geometry>
            </visual>
            <collision>
                <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> -->
                <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
                <geometry>
                    <cylinder radius="${wheeldiam/2}" length="${wheel_len}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${robot_wheel_mass}"/>
                <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> -->
                <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
                    <inertia
                        ixx="0.1" ixy="0.0" ixz="0.0"
                                  iyy="0.1" iyz="0.0"
                                            izz="0.1"
                    />
		    </inertial>
        </link>

        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="${0.2*x_reflect} ${0.3*y_reflect} -${wheeldiam/2+.05}" rpy="0 0 0"/>
            <limit effort="10000" velocity="1000"/>
            <dynamics damping="1.0" friction="1.0"/>
        </joint>

        <!-- This block connects the wheel joint to an actuator (motor), which informs both
        simulation and visualization of the robot -->
       <!-- <transmission name="${prefix}_${suffix}_wheel_trans">
           <type>transmission_interface/SimpleTransmission</type>
           <actuator name="${prefix}_${suffix}_wheel_motor">
               <mechanicalReduction>1</mechanicalReduction>
               <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
           </actuator>
           <joint name="${prefix}_${suffix}_wheel_joint">
               <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
           </joint>
       </transmission> -->
    </xacro:macro>

    <xacro:wheel prefix="left" suffix="front" x_reflect="1" y_reflect="1"/>
    <xacro:wheel prefix="right" suffix="front" x_reflect="1" y_reflect="-1"/>
    <xacro:wheel prefix="left" suffix="back" x_reflect="-1" y_reflect="1"/>
    <xacro:wheel prefix="right" suffix="back" x_reflect="-1" y_reflect="-1"/>

    <gazebo>
        <plugin name="gps_sim" filename="libhector_gazebo_ros_gps.so">
            <alwaysOn>1</alwaysOn>
            <updateRate>10.0</updateRate>
            <bodyName>base_link</bodyName>
            <frameId>base_link</frameId>
            <topicName>mobile_robot_gps/fix</topicName>
            <velocityTopicName>mobile_robot_gps/fix_velocity</velocityTopicName>

            <offset>0 0 0</offset>
            <drift>0 0 0</drift>
            <gaussianNoise>0.05 0.05 0.05</gaussianNoise>
            <velocityDrift>0.0001 0.0001 0.0001</velocityDrift>
            <velocityOffset>0 0 0</velocityOffset>
            <velocityGaussianNoise>0.05 0.05 0.05</velocityGaussianNoise>

            <referenceLatitude>0.0</referenceLatitude>
            <referenceLongitude>0.0</referenceLongitude>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="mag_sim" filename="libhector_gazebo_ros_magnetic.so">
            <updateRate>10.0</updateRate>
            <bodyName>base_link</bodyName>
            <frameId>base_link</frameId>
            <topicName>mobile_robot_mag</topicName>
            <offset>0 0 0</offset>
            <drift>0 0 0</drift>
            <gaussianNoise>0.05 0.05 0.05</gaussianNoise>
            <referenceHeading>90.0</referenceHeading>
        </plugin>
    </gazebo>

    <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>base_link</bodyName>
      <topicName>mobile_robot_imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
        <initialOrientationAsReference>false</initialOrientationAsReference>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
    </plugin>
  </gazebo>

   <gazebo>
  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
    <updateRate>10.0</updateRate>
    <robotNamespace>/</robotNamespace>
    <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
    <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
    <leftRearJoint>left_back_wheel_joint</leftRearJoint>
    <rightRearJoint>right_back_wheel_joint</rightRearJoint>
    <wheelSeparation>0.4</wheelSeparation>
    <wheelDiameter>0.15</wheelDiameter>
    <robotBaseFrame>base_link</robotBaseFrame>
    <torque>10</torque>
    <!-- <wheelAcceleration> 1  </wheelAcceleration> -->
    <topicName>cmd_vel</topicName>
    <broadcastTF>true</broadcastTF>
    <odometryTopic>mobile_robot/odom</odometryTopic>

    <covariance_x>0.0001</covariance_x>
    <covariance_y>0.0001</covariance_y>
    <covariance_yaw>0.01</covariance_yaw>
  </plugin>
</gazebo>


</robot>
